### ISSUE TITLE
update npm version

### ISSUE THREAD

**Issue by mrflix** [flyntwp/generator-flynt#23]
Please release a new version on npm so that the latest variable name changes are in there.

For example `$globalRuptureScale` is still called `$globalLayoutScale` in the latest published version.

**Comment by Qakulukiam** [comment]
Confirmed, sorry and thanks! Will update shortly.

**Comment by Qakulukiam** [comment]
fixed in [v0.2.0](https://github.com/flyntwp/generator-flynt/releases/tag/v0.2.0)
